### ISSUE TITLE
No any information how to build the project

### ISSUE THREAD

**Issue by ValeriyLapin** [StocksExchange/Android-app#2]
What should be placed to `key.properties`?
SIGNING_CONFIG_KEY_ALIAS, SIGNING_CONFIG_KEY_PASSWORD, SIGNING_CONFIG_STORE_FILE, SIGNING_CONFIG_STORE_PASSWORD, NEW_RELIC_TOKEN, ENCRYPTION_KEY?

**Comment by mars885** [comment]
Hey there. 

keys.properties is our private file that contains sensitive information. Create a file with its name in the root project with your values.

SIGNING_CONFIG_KEY_ALIAS, SIGNING_CONFIG_KEY_PASSWORD, SIGNING_CONFIG_STORE_FILE, SIGNING_CONFIG_STORE_PASSWORD are variables related to building a release version of the app. Details how to create the config can be found [here](https://developer.android.com/studio/publish/app-signing).

NEW_RELIC_TOKEN is a unique ID of the app for the NewRelic library. I'm pretty sure you can provide garbage value here and it will work.

ENCRYPTION_KEY is the key we use for encrypting some sensitive data. Instructions on how to generate one is [here](https://github.com/tozny/java-aes-crypto).
